[tool.poetry]
name = "algorithmic-excercises"
version = "0.1.0"
description = ""
authors = ["percebus"]
license = "SEE LICENSE IN LICENSE.md"
readme = "README.md"
packages = [{include = "problems"}]

[tool.poetry.dependencies]
python = "~3.12"

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
pylint = "^3.0.2"
pytest-bdd = "^7.0.1"
pytest = "^7.4.3"
setuptools = "^69.0.3"

[virtualenvs]
create = true
in-project = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
